/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.Slovo;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author andri
 */
public class KlijentskaForma extends javax.swing.JFrame {

    private int brojPokusaja = 0;
    private int brojPogodjenih = 0;
    List<Character> pokusanaSlova = new ArrayList<>();

    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSlovo1 = new javax.swing.JTextField();
        txtSlovo2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSlovo3 = new javax.swing.JTextField();
        txtSlovo4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSlovo5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUnesiSlovo = new javax.swing.JTextField();
        btnPogadjaj = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblBrojPokusaja = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblKoriscenaSlova = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("1. slovo");

        txtSlovo1.setEditable(false);

        txtSlovo2.setEditable(false);
        txtSlovo2.setPreferredSize(new java.awt.Dimension(64, 39));

        jLabel2.setText("2. slovo");

        jLabel3.setText("3. slovo");

        txtSlovo3.setEditable(false);
        txtSlovo3.setPreferredSize(new java.awt.Dimension(64, 39));

        txtSlovo4.setEditable(false);
        txtSlovo4.setPreferredSize(new java.awt.Dimension(64, 39));

        jLabel4.setText("4. slovo");

        txtSlovo5.setEditable(false);
        txtSlovo5.setPreferredSize(new java.awt.Dimension(64, 39));

        jLabel5.setText("5. slovo");

        jLabel6.setText("Pogadjaj");

        btnPogadjaj.setText("Pogadjaj");
        btnPogadjaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPogadjajActionPerformed(evt);
            }
        });

        jLabel7.setText("Preostali broj pokusaja");

        lblBrojPokusaja.setText("10");

        jLabel8.setText("Koriscena slova");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSlovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtUnesiSlovo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSlovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSlovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSlovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSlovo5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnPogadjaj))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(33, 33, 33)
                        .addComponent(lblBrojPokusaja))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(72, 72, 72)
                        .addComponent(lblKoriscenaSlova, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtSlovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSlovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtSlovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtSlovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtSlovo5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnesiSlovo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPogadjaj))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblBrojPokusaja))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblKoriscenaSlova, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPogadjajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPogadjajActionPerformed
        
            
        brojPokusaja++;
        lblBrojPokusaja.setText(10 - brojPokusaja + "");
        if (brojPokusaja > 10) {
            JOptionPane.showMessageDialog(this, "Nema vise pokusaja");
            btnPogadjaj.setEnabled(false);
            return;
        }
        String slovoText = txtUnesiSlovo.getText();
//        char slovo = slovoText.charAt(0);
        char slovo = Character.toUpperCase(slovoText.charAt(0));
        Slovo s = new Slovo(-1, slovo);
        
        if (pokusanaSlova.contains(slovo)) {
            JOptionPane.showMessageDialog(this, "To slovo je vec iskoriceno");
            return;
        }
        
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.POGADJAJ, s);
        Komunikacija.getInstance().posaljiZahtev(kz);

        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        s = (Slovo) so.getOdgovor();

        pokusanaSlova.add(slovo);
        
        if (s.getPozicija() == -1) {
            JOptionPane.showMessageDialog(this, "Nije pogodjeno");
        } else {
            brojPogodjenih++;
            JOptionPane.showMessageDialog(this, "Jeste pogodjeno");
            if (s.getPozicija() == 1) {
                txtSlovo1.setText(s.getSlovo() + "");
            }
            if (s.getPozicija() == 2) {
                txtSlovo2.setText(s.getSlovo() + "");
            }
            if (s.getPozicija() == 3) {
                txtSlovo3.setText(s.getSlovo() + "");
            }
            if (s.getPozicija() == 4) {
                txtSlovo4.setText(s.getSlovo() + "");
            }
            if (s.getPozicija() == 5) {
                txtSlovo5.setText(s.getSlovo() + "");
            }
            if (brojPogodjenih >= 5) {
                JOptionPane.showMessageDialog(this, "Pobedili ste ");
                btnPogadjaj.setEnabled(false);
                return;
            }
        }
        txtUnesiSlovo.setText("");
        String textZaLabelu = "";
        for (Character k : pokusanaSlova) {
            textZaLabelu = textZaLabelu + k;//moglo je ovde + k + ", "; 
            textZaLabelu = textZaLabelu + ", ";
        }
        lblKoriscenaSlova.setText(textZaLabelu);
        
        
    }//GEN-LAST:event_btnPogadjajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPogadjaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblBrojPokusaja;
    private javax.swing.JLabel lblKoriscenaSlova;
    private javax.swing.JTextField txtSlovo1;
    private javax.swing.JTextField txtSlovo2;
    private javax.swing.JTextField txtSlovo3;
    private javax.swing.JTextField txtSlovo4;
    private javax.swing.JTextField txtSlovo5;
    private javax.swing.JTextField txtUnesiSlovo;
    // End of variables declaration//GEN-END:variables
}
