/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.Point;
import java.io.IOException;
import java.lang.System.Logger.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import komunikacija.Komunikacija;
import model.SkriveniBroj;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author andri
 */
public class KlijentskaForma extends javax.swing.JFrame {

    int brojPokusaja = 0;
    int brojPogodjenih = 0;
    int cifra1;
    int cifra2;
    int cifra3;

    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablee = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablee.setRowHeight(40);
        tablee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablee);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableeMouseClicked
        // bajo moj isao sam na tabelu pa events pa mouse pa mouse clicked
        if (brojPokusaja < 5) {

            JTable tabela = (JTable) evt.getSource();
            Point point = evt.getPoint();
            int red = tabela.rowAtPoint(point);
            int kolona = tabela.columnAtPoint(point);
            if (red != -1 && kolona != -1) {
                System.out.println("Kordinate " + red + " " + kolona);

                KlijentskiZahtev kz = new KlijentskiZahtev();
                kz.setOperacija(Operacije.POGODI_BROJ);
                SkriveniBroj sb = new SkriveniBroj(kolona, red, -1);
                kz.setParam(sb);
                Komunikacija.getInstance().posaljiZahtev(kz);
                ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

                sb = (SkriveniBroj) so.getOdgovor();
                if (sb == null) {
                    tabela.setValueAt(-1, red, kolona);
                } else {
                    brojPogodjenih++;
                    if (brojPogodjenih == 1) {
                        cifra1 = sb.getVrednost();
                    } else if (brojPogodjenih == 2) {
                        cifra2 = sb.getVrednost();
                    } else {
                        cifra3 = sb.getVrednost();
                    }
                    tabela.setValueAt(sb.getVrednost(), red, kolona);
                    if (brojPogodjenih == 3) {
                        int najveca = Math.max(cifra1, Math.max(cifra2, cifra3));
                        int najmanja = Math.min(cifra1, Math.min(cifra2, cifra3));
                        int srednja = cifra1 + cifra2 + cifra3 - najveca - najmanja;
                        int broj = srednja * 100 + najveca * 10 + najmanja;
                        JOptionPane.showMessageDialog(null, "Pobedili ste"
                                + ", sifra je " + broj);
                        zavrsiPartiju();
                        return;
                        // KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.NOVA_IGRA, null);
                        //Komunikacija.getInstance().posaljiZahtev(kz);
                        //resetujFormu(); tu bi isao copy paste iz initialComponents
                        //i pored toga treba da se resetuje brojPokusaja na 0 i brojPogodjenih na 0
                    }

                }
                brojPokusaja++;
            }
        }

        if (brojPokusaja >= 5) {
            JOptionPane.showMessageDialog(null, "Izgubili ste");

            zavrsiPartiju();
            ugasiEkran();
        }


    }//GEN-LAST:event_tableeMouseClicked

    private void ugasiEkran() {
        try {
            Komunikacija.getInstance().getS().close();
        } catch (IOException ex) {
            Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.dispose();
    }

    private void zavrsiPartiju() {
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.NOVA_IGRA, null);
        Komunikacija.getInstance().posaljiZahtev(kz);
        ocistiEkran();
    }
    
    private void ocistiEkran(){
       
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablee;
    // End of variables declaration//GEN-END:variables
}
