/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.Controller;
import java.util.List;
import server.PokreniServer;

/**
 *
 * @author andri
 */
public class ServerskaForma extends javax.swing.JFrame {

    private List<String> zadateReci;
    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        setLocationRelativeTo(null);
        popuniCombo();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbOdabranaRec = new javax.swing.JComboBox<>();
        btnPokreniIgru = new javax.swing.JButton();
        txtSlovo1 = new javax.swing.JTextField();
        txtSlovo2 = new javax.swing.JTextField();
        txtSlovo3 = new javax.swing.JTextField();
        txtSlovo4 = new javax.swing.JTextField();
        txtSlovo5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Odabrana rec je ");

        cmbOdabranaRec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnPokreniIgru.setText("Pokreni igru");
        btnPokreniIgru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniIgruActionPerformed(evt);
            }
        });

        txtSlovo1.setEditable(false);
        txtSlovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSlovo1ActionPerformed(evt);
            }
        });

        txtSlovo2.setEditable(false);
        txtSlovo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSlovo2ActionPerformed(evt);
            }
        });

        txtSlovo3.setEditable(false);
        txtSlovo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSlovo3ActionPerformed(evt);
            }
        });

        txtSlovo4.setEditable(false);
        txtSlovo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSlovo4ActionPerformed(evt);
            }
        });

        txtSlovo5.setEditable(false);
        txtSlovo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSlovo5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSlovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSlovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSlovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSlovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSlovo5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(cmbOdabranaRec, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btnPokreniIgru)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbOdabranaRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPokreniIgru))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSlovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlovo5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSlovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSlovo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSlovo1ActionPerformed

    private void txtSlovo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSlovo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSlovo2ActionPerformed

    private void txtSlovo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSlovo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSlovo3ActionPerformed

    private void txtSlovo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSlovo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSlovo4ActionPerformed

    private void txtSlovo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSlovo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSlovo5ActionPerformed

    private void btnPokreniIgruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniIgruActionPerformed
        String odabranaRec = (String) cmbOdabranaRec.getSelectedItem();
        Controller.getInstance().setOdabranaRec(odabranaRec);
        txtSlovo1.setText(odabranaRec.charAt(0) + "");
        txtSlovo2.setText(odabranaRec.charAt(1) + "");
        txtSlovo3.setText(odabranaRec.charAt(2) + "");
        txtSlovo4.setText(odabranaRec.charAt(3) + "");
        txtSlovo5.setText(odabranaRec.charAt(4) + "");
        
        PokreniServer ps = new PokreniServer();
        ps.start();
    }//GEN-LAST:event_btnPokreniIgruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreniIgru;
    private javax.swing.JComboBox<String> cmbOdabranaRec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtSlovo1;
    private javax.swing.JTextField txtSlovo2;
    private javax.swing.JTextField txtSlovo3;
    private javax.swing.JTextField txtSlovo4;
    private javax.swing.JTextField txtSlovo5;
    // End of variables declaration//GEN-END:variables

    private void popuniCombo() {
        cmbOdabranaRec.removeAllItems();
        zadateReci = Controller.getInstance().getZadateReci();
        for (String reci : zadateReci) {
            cmbOdabranaRec.addItem(reci);
        }
        
    }
}
